carreras/urls.py
from django.urls import path
from .views import CarreraListView, CarreraDetailView, AreaDetailView


carreras_patterns = ([
    path('', CarreraListView.as_view(), name='carreras_list'),
    path('<int:pk>/<slug:slug>/', CarreraDetailView.as_view(), name='carrera'),
    path('category/<int:pk>/<slug:slug>/', AreaDetailView.as_view(), name='area'),
], "carreras")

core/urls.py
from django.urls import path
from .views import HomePageView
 
urlpatterns = [
 
    #Paths del core
    path('', HomePageView.as_view(), name="home"),
]

webemba/urls.py
from django.contrib import admin
from django.urls import path, include
from news.urls import news_patterns
from carreras.urls import carreras_patterns
from pages.urls import pages_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    #Paths del core
    path('', include('core.urls')),
    # Path de news
    path('news/', include(news_patterns)),
    # Path de carreras
    path('carreras/', include(carreras_patterns)),
    #Pat de paginas
    path('pages/', include(pages_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carreras/models.py
from django.db import models
from django.utils import timezone #Imporza libreria de fechas
from django.contrib.auth.models import User #importar usuarios creados con el panel de admin
from ckeditor.fields import RichTextField

# Create your models here.
class Area(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "area"
        verbose_name_plural = "areas"
        ordering = ['-created']

    def __str__(self):
        return self.name

class Carrera(models.Model):
    name = models.CharField(max_length=200, verbose_name="Título")
    subtitle = models.CharField(max_length=200, verbose_name="Subtítulo", null=True, blank=True)
    content = RichTextField(verbose_name="Contenido", null=True, blank=True)
    turnos = RichTextField(verbose_name="Turnos", null=True, blank=True)
    planMaterias=models.CharField(max_length=200, verbose_name="Título Plan de Estudio", null=True, blank=True)
    linkPlanMaterias=models.CharField(max_length=200, verbose_name="Link Plan de Estudio", null=True, blank=True)
    linkRegimenCursada=models.CharField(max_length=200, verbose_name="Link Régimen de Cursada", null=True, blank=True)
    published = models.DateTimeField(verbose_name="Fecha de Publicación", default=timezone.now)
    imageCarrera = models.ImageField(verbose_name="Imagen", upload_to="carreras", null=True, blank=True)
    bannerCarrera = models.ImageField(verbose_name="Banner de Carrera", upload_to="carreras", null=True, blank=True)
    color = models.CharField(max_length=10, verbose_name="Color")
    #Enlazar con Foreign Key en cascada
    areaCarrera = models.ForeignKey(Area, verbose_name="Área", related_name="get_areas", on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name="Fecha de Creación", auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "carrera"
        verbose_name_plural = "carreras"
        ordering = ['-created']

    def __str__(self):
        return self.name

news/models.py
import imp
from django.db import models
from django.utils import timezone #Imporza libreria de fechas
from django.contrib.auth.models import User #importar usuarios creados con el panel de admin
from ckeditor.fields import RichTextField


class CategoryNews(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "categoria"
        verbose_name_plural = "categorias"
        ordering = ['-created']

    def __str__(self):
        return self.name

class TagNews(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tags"
        ordering = ['-created']

    def __str__(self):
        return self.name

class AreaNews(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "area"
        verbose_name_plural = "areas"
        ordering = ['-created']

    def __str__(self):
        return self.name

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    subtitle = models.CharField(max_length=200, verbose_name="Subtítulo")
    content = RichTextField(verbose_name="Contenido")
    published = models.DateTimeField(verbose_name="Fecha de Publicación", default=timezone.now)
    imageNews = models.ImageField(verbose_name="Imagen", upload_to="news", null=True, blank=True)
    #Enlazar con Foreign Key en cascada
    authorNews = models.ForeignKey(User, verbose_name="Autor", on_delete=models.CASCADE)
    areaNews = models.ManyToManyField(AreaNews, verbose_name="Area", related_name="get_area", null=True, blank=True)
    categoriesNews = models.ManyToManyField(CategoryNews, verbose_name="Categorias", related_name="get_categories")
    tagsNews = models.ManyToManyField(TagNews, verbose_name="Tags", related_name="get_tags")
    created = models.DateTimeField(verbose_name="Fecha de Creación", auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "noticia"
        verbose_name_plural = "noticias"
        ordering = ['-created']

    def __str__(self):
        return self.title

carreras/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render
from .models import Carrera, Area
from news.models import News
# Create your views here.
class CarreraListView(ListView):
    model = Carrera
    template_name = 'carreras/carreras_list.html'

class CarreraDetailView(DetailView):
    model = Carrera


class AreaDetailView(DetailView):
    model = Area

carreras/templates/carreras/carrera_detail copy.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

  <main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <div style="background-color: {{carrera.color}};" class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Carreras</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="centrarImg">
            {%if carrera.imageCarrera.url != null %}
              <img src="{{ carrera.imageCarrera.url }}" class="img-fluid" alt="">
            {%endif%}
          </div>
          <div class="content course-details">
            <h3 style="color: {{carrera.color}}" >{{carrera.name}}</h3>
            <p>
              {{object.content|safe}}
            </p>
          </div>
        </div>
      </div>
    </section><!-- End About Section -->

    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">
        <div class="content course-details">
          <h3 style="color: {{carrera.color}}" >Noticias de {{ carrera.areaCarrera.first.name }}</h3>
        </div>
        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% comment %} {% load news_extras %}
          {% get_news_list as news_list %} {% endcomment %}
          {% load news_extras %}
          {% get_news_list as news_list %}
          {% get_news_area_list as news_area_list %}
          {% for news in news_list|slice:3 %}
          {% if news.areaNews.first.name == carrera.areaCarrera.first.name %}
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">
              <img src="{% if news.imageNews.url != null %}
              {{ news.imageNews.url }}
              {% endif %}" class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h4 style="background-color: {{carrera.color}}">{{ news.categoriesNews.first.name }}</h4>
                  <!-- <p class="price">$169</p> -->
                </div>
                <h3><a href="{% url 'news:news' news.id news.title|slugify %}">{{news.title}}</a></h3>
              </div>
            </div>
          </div> <!-- End Course Item-->
          {{ news_area_list.count }}
          {% endif %}
          {% endfor %}
          <div class="separador">
            <br>
            <br>
          </div>


        </div>

      </div>
    </section><!-- End Courses Section -->

    <div class="separador">
      <br>
      <br>
    </div>
  <!-- Menú de paginación -->
  
  {% if news_list.count == 5 %}
  <!--is_paginated es para indicar que lo hace solo si hay mas numeros de instancias q permitan paginar-->
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <!--has_previos es para saber si existe una pagina antes, y has_next si existe una dsp
        Ademas si le agregamos_number sirve para saber el numero de pagina-->
          <li class="page-item ">
          <!--Todo lo referente al paginador se gestiona con el objeto page_obj-->
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
          </li>
        {% endif %}
        <!--Este es el bucle para recorrer las paginas. Page_range es la cantidad de paginas-->
        {% for i in paginator.page_range %}
          <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}



  </main><!-- End #main -->
  {% endblock %}

carreras/templates/carreras/carrera_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

  <main id="main">
    <!-- ======= Breadcrumbs ======= -->    
    <div class="breadcrumscarrera">
      <div class="container">
        <div class="row">
          {%if carrera.bannerCarrera.url != null %}
          <img src="{{ carrera.bannerCarrera.url }}" class="img-fluid" alt="...">
          {%endif%}
          <div class="col-xs-12 col-sm-6 col-md-4 colcarrera">
            <h3></h3>
            <p>{{carrera.content|safe}}
            </p>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-4 colcarrera">
            <h3>Turnos</h3>
            <p>{{carrera.turnos|safe}}
            </p>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-4 colcarrera">
            <h3>Plan de Materias</h3>
            <a href="{{carrera.linkPlanMaterias}}" target="_blank" class="btnPlanCarrera"><p>{{carrera.planMaterias}}</p></a>
            <br>
            <a href="{{carrera.linkRegimenCursada}}" target="_blank" class="btnRegimenCarrera">Ver régimen de cursada</a>
          </div>
        </div>
      </div>
    </div>




  </main><!-- End #main -->
  {% endblock %}

carreras/templates/carreras/carreras_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Mapa de Carreras</h2>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">
        <div class="row">
          <div class="centrarImg">
              <img src="{% static 'core/img/mapacarreras.jpg' %}" class="img-fluid" alt="">
          </div>
        </div>
      </div>
    </section><!-- End About Section -->
    <!-- ======= Courses Section ======= -->
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% comment %} {% load news_extras %}
          {% get_news_list as news_list %} {% endcomment %}
          {% for carrera in carrera_list %}
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">
              {%if carrera.imageCarrera.url != null %}
                <img src="{{ carrera.imageCarrera.url }}" class="img-fluid" alt="">
              {%endif%}
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h4 style="background-color: {{carrera.color}}">{{ carrera.areaCarrera.name }}</h4>
                  <!-- <p class="price">$169</p> -->
                </div>

                <h3><a href="{% url 'carreras:carrera' carrera.id carrera.name|slugify %}">{{carrera.name}}</a></h3>
                <!-- <p>Et architecto provident deleniti facere repellat nobis iste. Id facere quia quae dolores dolorem tempore.</p>
                <div class="trainer d-flex justify-content-between align-items-center">
                  <div class="trainer-profile d-flex align-items-center">
                    <img src="assets/img/trainers/trainer-1.jpg" class="img-fluid" alt="">
                    <span>Antonio</span>
                  </div>
                  <div class="trainer-rank d-flex align-items-center">
                    <i class="bx bx-user"></i>&nbsp;50
                    &nbsp;&nbsp;
                    <i class="bx bx-heart"></i>&nbsp;65
                  </div>
                </div> -->
              </div>
            </div>
          </div> <!-- End Course Item-->
          {% endfor %}
          <div class="separador">
            <br>
            <br>
          </div>
        <!-- Menú de paginación -->
        {% if is_paginated %}
        <!--is_paginated es para indicar que lo hace solo si hay mas numeros de instancias q permitan paginar-->
          <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
              <!--has_previos es para saber si existe una pagina antes, y has_next si existe una dsp
              Ademas si le agregamos_number sirve para saber el numero de pagina-->
                <li class="page-item ">
                <!--Todo lo referente al paginador se gestiona con el objeto page_obj-->
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
              {% endif %}
              <!--Este es el bucle para recorrer las paginas. Page_range es la cantidad de paginas-->
              {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item ">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}

        </div>

      </div>
    </section><!-- End Courses Section -->

  </main><!-- End #main -->

  {% endblock %}